$("Submit").css("color, black");
$(".twoimg").hide();
$(".thrimg").hide();
$(".forimg").hide();
$(".fivimg").hide();
$(".siximg").hide();
$(".sevimg").hide();
$(".ateimg").hide();

     $(".age").css("background-color", "black");
     $(".age").css("color", "white");
     $(".height").css("background-color", "black");
     $(".height").css("color", "white");
     $(".cheat").css("background-color", "black");
     $(".cheat").css("color", "white");
     $(".smart").css("background-color", "black");
     $(".smart").css("color", "white");
$(".Submit").click(function(){
    var ageInput = $(".age").val();
    var heightInput = $(".height").val();
    var cheatInput = $(".cheat").val();
    var smartInput = $(".smart").val();
     if (ageInput === "14" && heightInput === "tall" && cheatInput === "cheated on" && smartInput === "school smart"){
         $(".msg").text("Congrats, you are Jamal! You are a kinda clingy and very underestemated. You are also determined and you don't give up when you put your mind to something!");
           $(".siximg").fadeIn();
        $(".img").hide();
        $(".twoimg").hide();
        $(".thrimg").hide();
        $(".forimg").hide();
        $(".fivimg").hide();
        $(".sevimg").hide();
        $(".ateimg").hide();
        $(".nineimg").hide();
         $("body").css("border", "green");
     $(".age").css("background-color", "green");
     $(".age").css("color", "black");
     $(".height").css("background-color", "green");
     $(".height").css("color", "black");
     $(".cheat").css("background-color", "green");
     $(".cheat").css("color", "black");
     $(".smart").css("background-color", "green");
     $(".smart").css("color", "black");
} else if (ageInput === "15" && heightInput === "tall" && cheatInput === "cheater" && smartInput === "street smart"){
    $(".msg").text("Congrats, you are Cesar! You are tough and you don't like asking for help. You would do anything to keep your friends safe, even if it means breakin' a few hearts in the process!");
        $(".twoimg").fadeIn();
        $(".img").hide();
        $(".siximg").hide();
        $(".thrimg").hide();
        $(".forimg").hide();
        $(".fivimg").hide();
        $(".sevimg").hide();
        $(".ateimg").hide();
        $(".nineimg").hide();
         $(".age").css("background-color", "red");
     $(".age").css("color", "black");
     $(".height").css("background-color", "red");
     $(".height").css("color", "black");
     $(".cheat").css("background-color", "red");
     $(".cheat").css("color", "black");
     $(".smart").css("background-color", "red");
     $(".smart").css("color", "black");
} else if (ageInput === "15" && heightInput === "short" && cheatInput === "cheater" && smartInput === "school smart"){
    $(".msg").text("Congrats, you are Ruby! You are super smart and you always know how to talk yourself out of a bad situation. You are also a little obsessed with finding the right soul mate!");
    $(".thrimg").fadeIn();
    $(".img").hide();
       $(".siximg").hide();
       $(".twoimg").hide();
       $(".forimg").hide();
       $(".ateimg").hide();
       $(".fivimg").hide();
       $(".sevimg").hide();
       $(".nineimg").hide();
     $(".age").css("background-color", "skyblue");
     $(".age").css("color", "black");
     $(".height").css("background-color", "skyblue");
     $(".height").css("color", "black");
     $(".cheat").css("background-color", "skyblue");
     $(".cheat").css("color", "black");
     $(".smart").css("background-color", "skyblue");
     $(".smart").css("color", "black");
} else if (ageInput === "14" && heightInput === "short" && cheatInput === "cheated on" && smartInput === "street smart"){
    $(".msg").text("Congrats, you are Monse! You are very cautious and mature. You love to help others out of bad situations and fix all of the problems around you. You are also one of the most loyalest friends that anyone could ever ask for!");
     $(".forimg").fadeIn();
     $(".img").hide();
     $(".siximg").hide();
     $(".twoimg").hide();
     $(".thrimg").hide();
     $(".fivimg").hide();
     $(".ateimg").hide();
     $(".sevimg").hide();
     $(".nineimg").hide();
     $(".age").css("background-color", "purple");
     $(".age").css("color", "black");
     $(".height").css("background-color", "purple");
     $(".height").css("color", "black");
     $(".cheat").css("background-color", "purple");
     $(".cheat").css("color", "black");
     $(".smart").css("background-color", "purple");
     $(".smart").css("color", "black");
} else if (ageInput === "15" && heightInput === "short" && cheatInput === "cheater" && smartInput === "street smart"){
    $(".msg").text("Congrats, you are Jasmine! You are a very charismatic person. Besides the fact that you have a lot of struggles no one knows about and have trouble fitting in, you are always the life of the party and a great dancer!");
    $(".sevimg").fadeIn();
     $(".img").hide();
     $(".siximg").hide();
     $(".twoimg").hide();
     $(".thrimg").hide();
     $(".fivimg").hide();
     $(".forimg").hide();
     $(".ateimg").hide();
     $(".nineimg").hide();
     $(".age").css("background-color", "blue");
     $(".age").css("color", "black");
     $(".height").css("background-color", "blue");
     $(".height").css("color", "black");
     $(".cheat").css("background-color", "blue");
     $(".cheat").css("color", "black");
     $(".smart").css("background-color", "blue");
     $(".smart").css("color", "black");
} else if (ageInput === "14" && heightInput === "tall" && cheatInput === "cheated on" && smartInput === "street smart"){
     $(".msg").text("Congrats, you are Olivia! You are a very innocent and honest person. You are usually pretty oblivious to whats going on and what everyone loves about you is ur kindness and amazing friendship!");
     $(".ateimg").fadeIn();
     $(".img").hide();
     $(".siximg").hide();
     $(".twoimg").hide();
     $(".thrimg").hide();
     $(".fivimg").hide();
     $(".forimg").hide();
     $(".sevimg").hide();
     $(".nineimg").hide();
     $(".age").css("background-color", "pink");
     $(".age").css("color", "black");
     $(".height").css("background-color", "pink");
     $(".height").css("color", "black");
     $(".cheat").css("background-color", "pink");
     $(".cheat").css("color", "black");
     $(".smart").css("background-color", "pink");
     $(".smart").css("color", "black");
} else if (ageInput === "14" && heightInput === "tall" && cheatInput === "cheater" && smartInput === "street smart"){
    $(".msg").text("Congrats, you are Latrelle! You are a sneaky, cold hearted person. You will do whatever it takes to prove you are the best. You are ruthless!");
    $(".nineimg").fadeIn();
     $(".img").hide();
     $(".siximg").hide();
     $(".twoimg").hide();
     $(".thrimg").hide();
     $(".fivimg").hide();
     $(".forimg").hide();
     $(".sevimg").hide();
     $(".ateimg").hide();
     $(".age").css("background-color", "yellow");
     $(".age").css("color", "black");
     $(".height").css("background-color", "yellow");
     $(".height").css("color", "black");
     $(".cheat").css("background-color", "yellow");
     $(".cheat").css("color", "black");
     $(".smart").css("background-color", "yellow");
     $(".smart").css("color", "black");
} else{
    $(".msg").text("I'm sorry but you unfortunately don't qualify to be any character on 'On My Block'. But the good news is that you are your own unique person! Congrats on that!");
     $(".fivimg").fadeIn();
     $(".img").hide();
     $(".siximg").hide();
     $(".twoimg").hide();
     $(".thrimg").hide();
     $(".forimg").hide();
     $(".sevimg").hide();
     $(".ateimg").hide();
     $(".nineimg").hide();
}
});